### PR TITLE
Art develop

### PR DESCRIPTION
**Pull request by artthik**
- Added .idea files to .gitignore so no IDE project files are commited

- Added mongoose.Promise = Promise in index.js to get rid of the DeprecatedWarning
bildschirmfoto 2017-03-04 um 01 04 02

- Added chapter preconditions to README.md to make it idiot proof.

Greets Art.

### CODE REVIEW

**Comment by peschmae** [comment]
I've made a small change to gitignore (ignore the whole .idea folder), and mentioned docker in the README

I'll merge it as soon as travis built successfully

**Comment by artthik** [comment]
Why didn't I think of just removing the whole folder structure? ;)

**Comment by artthik** [comment]
One last question: Who accepts the Pull request? Shall I add them myself after the travis tests or is it meant that we only create the PR, you review it and then add them to the base branch yourself?
If so, maybe remove the rights to merge them for us, before we run into an accident.

**Comment by peschmae** [comment]
I'm not entirely sure, how we wan't to handle it, maybe @hairmare can chip in here.

At work, we normally do code reviews an all pull requests, on one hand to make sure, that the formatting is congruent, and on the other to distribute the know how throughout the team.

For now, I'll go ahead and merge this pull request.

I think it's best to work with feature branches (admittedly I'm a fan of [gitflow](http://nvie.com/posts/a-successful-git-branching-model/)), and keep them as atomic as possible.
But that's something you can decide within your team, if you wan't to adopt a specific branching strategy. Just the master/develop setup we have, is basically gitflow, the rest is up to you.

**Comment by artthik** [comment]
Thanks, I'll make sure to discuss gitflow and PR process with my team. @lebalz @kevin-meister @Manning94 @doutzi

**Comment by hairmare** [comment]
I usually create a [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) to ignore IDE specific things. While having `.idea` in `.gitignore` does not hurt, it's less work to configure that globally and helps keep `.gitignore` decluttered rather than having everyone merge $EDITOR_TMP_FILE ignores.

The [C4](https://rfc.zeromq.org/spec:42/C4/) which is somewhat similar to gitfow has the following on merging your own PRs (with Maintainers being those who have merge rights):

> Maintainers SHOULD NOT merge their own patches except in exceptional cases, 
> such as non-responsiveness from other Maintainers for an extended period (more 
> than 1-2 days).

We created a `develop` branch that is separate from `master` to make it easier for you to get stuff merged. `develop` is where you work against, `master` is what actually gets deployed. I think this makes it easier to not break `master` which should only ever have a stable state on it.

**Comment by artthik** [comment]
Thanks for the helpful tip with the `.gitignore_global`
OK, so we'll just make PRs from our development branch (`pse_dev`) to our base branch`develop` and leave further merging to you.

**Comment by hairmare** [comment]
Yupp, you merge to `develop` and we merge and tag to `master` to get production deployed after having ok'd what you present us at the sprint meeting.

**Pull request merged**
